admin_panel/urls.py
# En admin_panel/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'admin_panel'

urlpatterns = [
    path('profiles/', views.profile_list, name='profile_list'),
    path('profiles/<int:pk>/', views.profile_detail, name='profile_detail'),
    path('proveedores/', views.proveedores_list, name='proveedores_list'),
    path('productos/', views.productos_list, name='productos_list'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('lista_Usuarios/', views.lista_Usuarios, name='lista_Usuarios'),
    path('assign_superuser/<int:user_id>/', views.assign_superuser, name='assign_superuser'),
    
    # Agrega más URLs según sea necesario para los otros modelos (productos, proveedores, órdenes, etc.)
]

admin_panel/models.py
from django.db import models

# Create your models here.
class Business(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField()
    ruc= models.IntegerField()

    def __str__(self):
        return self.name

admin_panel/forms.py
from django import forms
from .models import Business
from shop.models import Profile

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'image', 'description', 'ruc']

class AdminPermissionForm(forms.ModelForm):
    is_admin = forms.BooleanField(required=False)

    class Meta:
        model = Profile
        fields = ['is_admin']

admin_panel/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from shop.models import Profile, Supplier, Product # Importa los modelos necesarios
from django.contrib import messages
from .models import Business
from .forms import BusinessForm
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AdminPermissionForm

def profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'profile_list.html', {'profiles': profiles})

def proveedores_list(request):
    proveedores = Supplier.objects.all()
    return render(request, 'productores.html', {'proveedores': proveedores})

def productos_list(request):
    productos = Product.objects.all()
    proveedores = Supplier.objects.all()
    return render(request, 'productos.html', {'productos': productos, 'proveedores': proveedores})

def profile_detail(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    return render(request, 'admin_panel/profile_detail.html', {'profile': profile})

@login_required
def nosotros(request):
    try:
        business = Business.objects.get()
    except Business.DoesNotExist:
        messages.error(request, 'El negocio solicitado no existe.')
        return redirect('some_fallback_view')

    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES, instance=business)
        if form.is_valid():
            form.save()
            messages.success(request, 'La información de la empresa ha sido actualizada correctamente.')
            return redirect('/')  # Ajusta la redirección según sea necesario
    else:
        form = BusinessForm(instance=business)
    
    context = {
        'form': form
    }
    return render(request, 'empresa.html', context)

@login_required
def lista_Usuarios(request):
    profiles = Profile.objects.all()
    return render(request, 'permisos.html', {'profiles': profiles})

@login_required
def assign_superuser(request, user_id):
    profile = get_object_or_404(Profile, user__id=user_id)
    if request.method == 'POST':
        profile.is_admin = not profile.is_admin
        profile.save()
        messages.success(request, f'Permiso de administrador {"asignado" if profile.is_admin else "revocado"} correctamente.')
        return redirect('/')
    return render(request, 'assign_superuser.html', {'profile': profile})

admin_panel/templates/assign_superuser.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Asignar Permiso de Administrador</h2>
    <p>¿Estás seguro de que quieres {% if profile.is_admin %}revocar{% else %}asignar{% endif %} permisos de administrador a {{ profile.user.username }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">{% if profile.is_admin %}Revocar{% else %}Asignar{% endif %} Permiso</button>
        <a href="{% url 'admin_panel:lista_Usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

admin_panel/templates/base-ad.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Admin Panel{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 sidebar">
                <div class="logo text-center my-3">
                    <img href="/" src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid ">
                </div>
                <h4 class="text-center">Bienvenido, {{ user.first_name }} {{ user.last_name }}</h4>
                <ul class="nav flex-column my-4">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Proveedores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Perfiles</a>
                    </li>
                </ul>
                <div class="center-links">
                    <a class="nav-link" href="#">Configuración de Perfil</a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button id="logout-button" class="logout-button" type="submit">Cerrar sesión</button>
                    </form>
                </div>
            </div>

    <div class="col-md-9">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

admin_panel/templates/empresa.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Actualizar Información de la Empresa</h5>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="form-group">
                          <label for="{{ form.name.id_for_label }}">Nombre de la Empresa</label>
                          <input type="text" class="form-control form-control-sm" id="name" name="name" required placeholder={{form.name}}>
                      </div>
                      <div class="form-group">
                          <label for="{{ form.image.id_for_label }}">Imagen</label>
                          {{ form.image }}
                      </div>
                      <div class="form-group">
                          <label for="{{ form.description.id_for_label }}">Descripción</label>
                          <textarea class="form-control" id="description" rows="3" placeholder={{form.description}}></textarea>
                      </div>
                      <div class="form-group">
                          <label for="{{ form.ruc.id_for_label }}">RUC</label>
                          {{ form.ruc }}
                      </div>
                      <button type="submit" class="btn btn-primary">Actualizar</button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/permisos.html
{% extends 'base-ad.html' %}

{% block content %}
<div class="container">
    <h2>Lista de Perfiles</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>DNI</th>
                <th>Teléfono</th>
                <th>Dirección</th>
                <th>Permiso Administrador</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in profiles %}
            <tr>
                <td>{{ profile.user.username }}</td>
                <td>{{ profile.dni }}</td>
                <td>{{ profile.phone_number }}</td>
                <td>{{ profile.address }}</td>
                <td>
                    {% if profile.is_admin %}
                        Sí
                    {% else %}
                        No
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'admin_panel:assign_superuser' user_id=profile.user.id %}" class="btn btn-primary btn-sm">{% if profile.is_admin %}Revocar{% else %}Asignar{% endif %} Permiso</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

admin_panel/templates/productores.html
{% extends 'base-ad.html' %}
{% load static %}

{% block content %}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <nav class="nav nav-tabs my-3">
                <a class="nav-link active" href="#">Todos</a>
                {% for proveedor in proveedores %}
                <a class="nav-link" href="#">{{proveedor.name}}</a>
                {% endfor %}
            </nav>
        </div>
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Proveedor</th>
                        <th>Contacto</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
                    <tr>
                        <td>{{proveedor.name}}</td>
                        <td>{{proveedor.contact_info}}</td>
                        <td>
                            <div class="action-buttons">
                                <button class="btn btn-success btn-sm">Editar</button>
                                <button class="btn btn-danger btn-sm">Eliminar</button>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No hay proveedores disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/productos.html
{% extends 'base-ad.html' %}
{% load static %}

{% block content %}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <nav class="nav nav-tabs my-3">
                <a class="nav-link active" href="#">Todos</a>
                {% for proveedor in proveedores %}
                <a class="nav-link" href="#">{{proveedor.name}}</a>
                {% endfor %}
            </nav>
        </div>
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Productos</th>
                        <th>Proveedor</th>
                        <th>Stock</th>
                        <th>Precio Unitario</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td>{{producto.name}}</td>
                        <td>{{producto.supplier}}</td>
                        <td>{{producto.quantity}}</td>
                        <td>{{producto.price}}</td>
                        <td>
                            <div class="action-buttons">
                                <button class="btn btn-success btn-sm">Editar</button>
                                <button class="btn btn-danger btn-sm">Eliminar</button>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No hay productos disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/profile_list.html
{% extends 'base-ad.html' %}
{% load static %}

{% block content %}
<div class="container mt-2">
    <h2>Listado de Perfiles</h2>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Usuario</th>
                <th>DNI</th>
                <th>Teléfono</th>
                <th>Dirección</th>
                <th>Crédito Aprobado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in profiles %}
            <tr>
                <td>{{ profile.id }}</td>
                <td>{{ profile.user.username }}</td>
                <td>{{ profile.dni }}</td>
                <td>{{ profile.phone_number }}</td>
                <td>{{ profile.address }}</td>
                <td>{% if profile.credit_approved %} Aprobado {% else %} Pendiente {% endif %}</td>
                <td>
                    <a href="/" class="btn btn-primary btn-sm">Inicio</a>
                    <!-- Agregar más acciones según sea necesario -->
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No hay perfiles disponibles.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}